const C={a:'1CLJ2BUCVuALR3XUQAcwKDvvEZuViSCUka',e:new Date('2026-04-30T23:59:59Z'),r:.02,t:[{s:7500,l:7500},{s:15000,l:15000},{s:30000,l:30000},{s:75000,l:75000}],ts:1e9,p:.523,h:733};
let S={w:!1,a:null,t:null,st:null,rc:null,b:0,py:[],p:C.p,hc:C.h};
const E={conW:$('conW'),disW:$('disW'),wDis:$('wDis'),wCon:$('wCon'),wAddr:$('wAddr'),bSats:$('bSats'),bUsd:$('bUsd'),cta:$('cta'),d:$('d'),h:$('h'),m:$('m'),sc:$('sc'),pP:$('pP'),pF:$('pF'),hC:$('hC'),payM:$('payM'),clsP:$('clsP'),pAmt:$('pAmt'),rcv:$('rcv'),cpA:$('cpA'),qr:$('qr'),fUp:$('fUp'),uA:$('uA'),cv:$('cv'),dl:$('dl'),tw:$('tw'),rL:$('rL'),cpR:$('cpR')};
function $(i){return document.getElementById(i)}
function init(){const u=new URLSearchParams(location.search),r=u.get('ref');if(r){S.rc=r}load();upUI();startCD();startPM();document.querySelectorAll('.tC').forEach(c=>c.onclick=()=>selT(c));document.querySelectorAll('.ah').forEach(h=>h.onclick=()=>h.parentElement.classList.toggle('open'));document.querySelectorAll('.tp').forEach(t=>t.onclick=()=>useTpl(t.dataset.t));E.conW.onclick=conW;E.disW.onclick=disW;E.cta.onclick=conW;E.clsP.onclick=()=>E.payM.style.display='none';E.cpA.onclick=()=>cp(C.a);E.cpR.onclick=()=>cp(E.rL.value);E.fUp.onchange=upImg;E.uA.onclick=()=>E.fUp.click();E.dl.onclick=dlMeme;E.tw.onclick=twMeme}
async function conW(){try{if(window.opnet){const a=await window.opnet.requestAccounts();if(a&&a[0]){S.w=!0;S.a=a[0];S.t='opnet';genRef();save();upUI();startPM();ntf('Wallet connected 👁️','s')}}else if(window.unisat){const a=await window.unisat.requestAccounts();if(a&&a[0]){S.w=!0;S.a=a[0];S.t='unisat';genRef();save();upUI();startPM();ntf('Wallet connected 👁️','s')}}else{ntf('Install OP_WALLET or Unisat','e');window.open('https://opnet.org','_blank')}}catch(e){ntf('Connection failed','e')}}
function disW(){S.w=!1;S.a=null;S.t=null;save();upUI();ntf('Disconnected','i')}
function genRef(){if(S.a){const h=S.a.substring(0,8).toUpperCase();E.rL.value=`${location.origin}${location.pathname}?ref=${h}`}}
function selT(c){if(!S.w){ntf('Connect wallet first','e');return}const s=parseInt(c.dataset.s),l=parseInt(c.dataset.l);let fl=l;if(S.rc)fl=Math.floor(l*(1+C.r));S.st={s,l:fl};E.pAmt.textContent=`${s.toLocaleString()} sats`;E.rcv.textContent=`${fl.toLocaleString()} LASER`;E.qr.innerHTML='';new QRCode(E.qr,{text:`bitcoin:${C.a}?amount=${s/1e8}`,width:250,height:250});E.payM.style.display='flex'}
let pInt=null;function startPM(){if(!S.w)return;if(pInt)clearInterval(pInt);chkPay();pInt=setInterval(chkPay,60000)}
async function chkPay(){if(!S.w)return;try{let txs=await fetchBC();if(!txs||!txs.length)txs=await fetchBS();if(!txs||!txs.length)txs=await fetchCY();if(txs&&txs.length)procTx(txs)}catch(e){console.error(e)}}
async function fetchBC(){try{const r=await fetch(`https://blockchain.info/rawaddr/${C.a}?cors=true`);if(!r.ok)return null;const d=await r.json();return d.txs.map(t=>({i:t.hash,tm:t.time,o:t.out.map(o=>({a:o.addr,v:o.value}))}))}catch{return null}}
async function fetchBS(){try{const r=await fetch(`https://blockstream.info/api/address/${C.a}/txs`);if(!r.ok)return null;const txs=await r.json();return txs.map(t=>({i:t.txid,tm:t.status.block_time,o:t.vout.map(o=>({a:o.scriptpubkey_address,v:o.value}))}))}catch{return null}}
async function fetchCY(){try{const r=await fetch(`https://api.blockcypher.com/v1/btc/main/addrs/${C.a}/full`);if(!r.ok)return null;const d=await r.json();return d.txs.map(t=>({i:t.hash,tm:new Date(t.confirmed).getTime()/1000,o:t.outputs.map(o=>({a:o.addresses?.[0],v:o.value}))}))}catch{return null}}
function procTx(txs){const rel=txs.filter(t=>t.o.some(o=>o.a===C.a)&&!S.py.find(p=>p.i===t.i));rel.forEach(t=>{const amt=t.o.filter(o=>o.a===C.a).reduce((s,o)=>s+o.v,0);if(amt>0)addPay(t.i,amt,t.tm)})}
function addPay(i,s,tm){let l=s*1;if(S.rc)l=Math.floor(l*(1+C.r));S.py.push({i,s,l,tm:tm||Date.now()/1000,c:!0});S.b+=l;updPrg(s);save();upUI();ntf(`🎉 ${l.toLocaleString()} LASER added!`,'s')}
function updPrg(s){const lS=s*1,nP=S.p+(lS/C.ts);S.p=Math.min(nP,1);if(!S.hc)S.hc+=1}
function startCD(){updCD();setInterval(updCD,1000)}
function updCD(){const n=Date.now(),e=C.e.getTime(),tL=e-n;if(tL<=0){E.d.textContent='00';E.h.textContent='00';E.m.textContent='00';E.sc.textContent='00';return}const d=Math.floor(tL/(1000*60*60*24)),h=Math.floor((tL%(1000*60*60*24))/(1000*60*60)),m=Math.floor((tL%(1000*60*60))/(1000*60)),s=Math.floor((tL%(1000*60))/1000);E.d.textContent=pad(d);E.h.textContent=pad(h);E.m.textContent=pad(m);E.sc.textContent=pad(s)}
function pad(n){return String(n).padStart(2,'0')}
let ctx,img;function upImg(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=ev=>{img=new Image();img.onload=()=>drawM();img.src=ev.target.result};r.readAsDataURL(f)}
function useTpl(t){img=new Image();img.onload=()=>drawM();img.src=`data:image/svg+xml,%3Csvg width='600' height='600' xmlns='http://www.w3.org/2000/svg'%3E%3Crect fill='%23222' width='600' height='600'/%3E%3Ctext x='300' y='300' text-anchor='middle' font-size='48' fill='white'%3E${t}%3C/text%3E%3C/svg%3E`}
function drawM(){if(!ctx)ctx=E.cv.getContext('2d');ctx.clearRect(0,0,600,600);if(img){ctx.drawImage(img,0,0,600,600);ctx.fillStyle='#f00';ctx.shadowBlur=20;ctx.shadowColor='#f00';ctx.beginPath();ctx.arc(200,220,15,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(400,220,15,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font='bold 36px Orbitron';ctx.fillStyle='#0f9';ctx.textAlign='center';ctx.fillText('LASER-FOCUSED ON 100K',300,550);ctx.font='48px sans-serif';ctx.fillText('👁️‍🗨️⚡',300,500)}}
function dlMeme(){if(!img){ntf('Upload photo first','e');return}E.cv.toBlob(b=>{const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='laser-eyes.png';a.click();URL.revokeObjectURL(u);ntf('Downloaded!','s')})}
function twMeme(){if(!img){ntf('Upload photo first','e');return}const t=encodeURIComponent("I'm laser-focused on 100K! 👁️‍🗨️⚡\n\n#LASER #LaserEyes #Bitcoin100K\n\n"+location.origin);window.open(`https://twitter.com/intent/tweet?text=${t}`,'_blank')}
function cp(t){navigator.clipboard.writeText(t).then(()=>ntf('Copied!','s'))}
function ntf(m,t='i'){const n=document.createElement('div');n.style.cssText=`position:fixed;top:100px;right:20px;padding:20px 30px;background:${t==='s'?'#0f9':t==='e'?'#f0a':'#0af'};color:#000;border-radius:10px;font-weight:700;z-index:9999;animation:slideIn .3s`;n.textContent=m;document.body.appendChild(n);setTimeout(()=>n.remove(),3000)}
function upUI(){if(S.w){E.wDis.style.display='none';E.wCon.style.display='block';E.wAddr.textContent=S.a.substring(0,8)+'...'+S.a.substring(S.a.length-8);const btc=S.b/1e8;E.bSats.textContent=`${S.b.toLocaleString()} sats`;E.bUsd.textContent=`$${(btc*67000).toFixed(2)}`;genRef()}else{E.wDis.style.display='block';E.wCon.style.display='none'}E.pP.textContent=`${(S.p*100).toFixed(1)}%`;E.pF.style.width=`${S.p*100}%`;E.hC.textContent=S.hc}
function save(){localStorage.setItem('laser',JSON.stringify(S))}
function load(){const sv=localStorage.getItem('laser');if(sv)S={...S,...JSON.parse(sv)}}
const st=document.createElement('style');st.textContent='@keyframes slideIn{from{transform:translateX(400px)}to{transform:translateX(0)}}';document.head.appendChild(st);
init();
